Deal more intelligently (i.e.: return $SMF_EXIT_ERR_CONFIG so SMF doesn't try to restart) with a return code of 6 from the OpenNMS init script which is returned in the case of configuration error.

diff --git a/svc-opennms b/svc-opennms
--- a/svc-opennms
+++ b/svc-opennms
@@ -20,7 +20,16 @@ if [ ! -f $configured ]; then
 fi
 
 if [ "$1" = "start" ]; then
-    exec $service -v start
+    $service -v start
+    ret=$?
+
+    if [ $ret -eq 6 ]; then
+        echo "Error: OpenNMS not properly configured.  See previous error messages for details." \
+            "  See opennms(1M)."
+        exit $SMF_EXIT_ERR_CONFIG
+    else
+        exit $ret
+    fi
 elif [ "$1" = "stop" ]; then
     $service -v stop
     ret=$?
